### ISSUE TITLE
Cannot create branch

### ISSUE THREAD

**Issue by joefincher** [Labdoo/Labdoo-3.0#14]
As we noticed during our last meeting, the branch dropdown labled Main on the Github page for Labdoo 3.0 does not offer the selection for Create branch. I have tried it from Gitpod using command line and it lets me create a branch by name, but I get permission not available messages when I try to commit

I tried the same thing under my forked version of Labdoo 3.0 and I was able to create a branch and push it to Github. 
The branch dropdown on the forked version offers Find or Create branch. It appears that there may be a user permission issue with the Labdoo 3,0 repository that prevents some users from
 creating and attaching a branch?

![image](https://user-images.githubusercontent.com/48815675/167723028-d9362d43-66f1-406d-adf7-2b614f2262b6.png)

**Comment by jrosgiralt** [comment]
Hi Joe, I tried it and I am able to create a branch. To create a brunch, go to https://github.com/Labdoo/Labdoo-3.0, click on the main button, and then where it says "Find or create a branch..." simply type the name of the branch you want to create. Then click on "Create branch". Here is a screenshot showing how to do this:

![image](https://user-images.githubusercontent.com/4118657/167780744-d766dbf4-aeab-4e41-9e6e-74f8b5dcfac6.png)

Also, this is explained here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository

**Comment by jrosgiralt** [comment]
Hi @joefincher , one more thing, I noticed you are not in the developers list. I just sent you an invite, please accept it first.

**Comment by joefincher** [comment]
Thanks Jordi!

That fixed the drop down and I now have branch Content-migration. I am now anointed and will move forward tomorrow morning.
Joe Fincherwww.uphill-intothewind.com

 

    On Wednesday, May 11, 2022, 01:16:05 PM GMT+7, Jordi ***@***.***> wrote:  
 
 


Hi @joefincher , one more thing, I noticed you are not in the developers list. I just sent you an invite, please accept it first.

**Comment by ijf8090** [comment]
@jrosgiralt can you repeat for me please?

**Comment by jrosgiralt** [comment]
Hi @ijf8090 , try now you should have read/write access to the repo (and therefore be able to create a branch)
