### ISSUE TITLE
Drupal 7 site is offline

### ISSUE THREAD

**Issue by ijf8090** [Labdoo/Labdoo-3.0#17]
The D7 site at https://ec2-3-121-181-157.eu-central-1.compute.amazonaws.com/ is offline with the following error

"Error message
PDOException: SQLSTATE[HY000]: General error: 1030 Got error 28 from storage engine: SELECT DISTINCT registry.name AS name, registry.filename AS filename FROM {registry} registry WHERE (type=:type AND ( filename like :filename OR name like :name )) ; Array ( [:type] => class [:name] => %MailSystem [:filename] => %.mail.% ) in mailsystem_get_classes() (line 282 of /var/www/lbd/profiles/labdoo/modules/contrib/mailsystem/mailsystem.module)."

This is most likely caused by my doing the following on June 26th
1) Enabling Backup and Migrate
2) Starting backup.

Wondering if the Amazon instance has sufficient capacity to run a backup?

**Comment by joefincher** [comment]
I have run Backup Migrate from the Labdoo 2.0 dev site. It was not a capacity issue then.
