### ISSUE TITLE
Labdoo 2.0 Drupal 7 Module Analysis

### ISSUE THREAD

**Issue by greggmarshall** [Labdoo/Labdoo-3.0#2]
I took the .make file for Labdoo 2.0, which is Drupal 7, and reviewed each module and theme.  Here are the results of that review:

## Themes

* bootstrap  -  bootstrap is D9 compatible, if you want to continue using Bootstrap 3,
             if you want Bootstrap 4 or 5, the barrio theme seems to be popular
* labdoo custom theme will need to be completely rebuilt since the template engine from Drupal 7 isn't used any more, replaced by Twig
* gin - recommended administration theme, extends claro, which will replace seven in D10

## Modules that have a Drupal 9 compatible version

* addtoany - D9 compatible
* antibot - D9 compatible
* calendar - D9 compatible in alpha release
* captcha - D9 compatible
* coder - D9 compatible, doesn't install as a module any more
* colorbox - D9 compatible
* computed_field - D9 compatible in alpha release
* conditional_fields - D9 compatible in alpha release
* context - D9 compatible
* ctools - D9 compatible
* delete_all  - D9 compatible
* devel - D9 compatible
* diff - D9 compatible
* disqus - D9 compatible, also has a new version in alpha release
* drush_language - D9 compatible, need to check compatibility with Drush 11 and might be redundant, https://www.drupal.org/project/drush_language/issues/3180653
* entityreference_filter - D9 compatible
* eva - D9 compatible
* extlink - D9 compatible
* field_group - D9 compatible
* flag - D9 compatible in beta release
* flexslider - D9 compatible
* google_analytics - D9 compatible
* homebox - D9 compatible with warning about using in production
* honeypot - D9 compatible
* imce - D9 compatible, might look at using core's media library instead
* lang_dropdown - D9 compatible
* legal - D9 compatible
* linkchecker - D9 compatible
* mailsystem - D9 compatible
* mass_contact - D9 compatible
* memcache - D9 compatible
* mimemail - D9 compatible
* node_export - D9 compatible
* node_view_permissions - D9 compatible, why?
* pathauto - D9 compatible
* plupload - D9 compatible
* publishcontent - D9 compatible, replace with content moderation?
* r4032login - D9 compatible
* recaptcha - D9 compatible
* reroute_email - D9 compatible
* role_delegation - D9 compatible
* search_autocomplete - D9 compatible
* sharethis - D9 compatible
* simplenews - D9 compatible
* smtp - D9 compatible
* spambot - D9 compatible
* subpathauto - D9 compatible
* token - D9 compatible
* user_restrictions - D9 compatible
* video_filter - D9 compatible
* view_unpublished - D9 compatible
* views_autocomplete_filters - D9 compatible
* views_slideshow - D9 compatible
* views_tree - D9 compatible in alpha version

Note that modules will need to be manually configured and configuration exported.  Do not attempt to use the existing Drupal 7 features, they will not work.

## Modules that do not have a Drupal 9 version or have been incorporated into Drupal core

* boost - replaced by D9 core caching
* boxes - no D8/D9 version
* countries - no D8/D9 version
* date - Moved into D9 core, if you want more functionality look at smart_date
* drupal_wall - no D8/D9 version
* drupalchat - no D8/D9 version, switch to rocket_chat?
* edit_profile - no D8/D9 version
* email - Moved into D9 core
* entity - Moved into D9 core, not sure why there's a D8/D9 version
* entityreference - Moved into D9 core
* entityreference_prepopulate - no D8/D9 version
* features - D9 compatible, but highly recommended not to use, replaced by core configuration management
* features_extra - no D8/D9 version, likely not needed
* field_collection - no D8/D9 version, usually replaced by paragraphs
* file_entity - D9 compatible but not recommended by maintainers, mostly moved into core, should probably use media instead
* gmap - no D8/D9 version, geolocation is recommended
* google_adwords - no D8/D9 version
* google_recaptcha - no D8/D9 version, replace with recaptcha module
* hide_submit - no D8/D9 version
* hybridauth - no D8/D9 version
* i18n - Moved into D9 core
* i18nviews - Moved into D9 core
* imagecache_actions - no D8/D9 version, replaced by image_effects
* imagemagick - D9 compatible, also there's imagick that uses the PHP extensio
* imce_mkdir - no D8/D9 version
* imce_wysiwyg - no D8/D9 version
* ip_geoloc - no D8/D9 version, might look at smart_ip for ip to location lookup
* jquery_update - no D8/D9 version, moved into core
* l10n_update - Moved into D9 core
* libraries - Moved into D9 core, there still is a D9 version for some functionality (never needed it)
* location - no D8/D9 version, replace with geolocation and address modules, see also https://www.drupal.org/project/location_migration for migration automation
* logintoboggan - no D8/D9 version
* menu_view_unpublished - no D8/D9 version look at view_unpublished
* migrate - Moved into D9 core, https://www.drupal.org/docs/upgrading-drupal/how-to-prepare-your-drupal-7-or-8-site-for-drupal-9
* migrate_d2d - Moved into D9 core
* module_filter - Moved into D9 core, not sure what D9 version adds
* node_gallery - no D8/D9 version right be replacable with a view
* nodeaccess_userreference - no D8/D9 version
* oauth2_loginprovider - no D8/D9 version
* og - D9 compatible, although mostly replaced in D8/D9 by group module (fewer than 1,000 D8/D9 sites use og va 12,000 group)
* og_extras - no D8/D9 version
* registration - no D8/D9 version, might look at https://www.drupal.org/project/smart_date_starter_kit
* rules - D9 compatible although not very well supported, might also look at eca module which is new
* search_config - no D8/D9 version
* services - D9 compatible, although REST is built into D9 core
* simplify - Moved into D9 core
* special_menu_items - Moved into D9 core
* stringoverrides - no D8/D9 version
* strongarm - no D8/D9 version, deprecated by core configuration management
* termcase - no D8/D9 version
* transliteration - no D8/D9 version, this may have been moved into core
* uuid - Moved into D9 core
* variable - no D8/D9 version
* views - Moved into D9 core
* views_dependent_filters - no D8/D9 version
* views_distinct - no D8/D9 version, there is an option in views for this
* wysiwyg using tinymce - Moved into D9 core although using CKEDITOR
* xautoload - no D8/D9 version, probably not needed since D9 has PSR-4 autoloading

**Comment by jrosgiralt** [comment]
great, let's discuss this during our meeting tomorrow. Thank you!

**Comment by jrosgiralt** [comment]
@greggmarshall , how worrysome is this kind of warning when requiring a module via composer?
```
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
```

**Comment by greggmarshall** [comment]
Reasonably common.  I usually ignore them.

sent from my phone
Gregg Marshall, CPMR, CPSC

**Comment by jrosgiralt** [comment]
Hi @greggmarshall ,

The module nodeaccess_userreference (https://www.drupal.org/project/nodeaccess_userreference) is not available in D8/D9 version. Any thoughts on how I can have this feature? The use case is as follows:

- I’d like to replicate a feature from the current Labdoo 2.0, which consists in a field in the dootronic content type that’s called “Additional editors”. This field allows an editor of the dootronic to add additional users that are then given edit rights of such a dootronic.

Thanks.

**Comment by greggmarshall** [comment]
@jrosgiralt  Take a look at https://www.drupal.org/project/access_by_ref.  I haven't used it but it looks like it might be a solution.
