### ISSUE TITLE
Push to main

### ISSUE THREAD

**Issue by joefincher** [Labdoo/Labdoo-3.0#20]
Accidentally pushed modules to main instead of my branch. I began work without checking out my branch 

It also appears I may have clobbered composer.json. scripts/dev-setup.sh blows up after starting ddev

**Comment by joefincher** [comment]
Performed git reset --hard HEAD^

Hopefully the wrong is righted, please confirm

**Comment by jrosgiralt** [comment]
@joefincher , perfect, thank you for undoing the commit, everything looks good, cheers!
