### ISSUE TITLE
Creating nodes automatically at building time

### ISSUE THREAD

**Issue by jrosgiralt** [Labdoo/Labdoo-3.0#24]
Hi @greggmarshall ,

I would like to create a node automatically at building time. For instance, in Labdoo we have a hub called "Grassroots Hub" which is generic and should always exist. I would like this node (which is of content type "hub") to be created automatically when Labdoo 3.0 is being built and initialized. What is a good way to do this in Drupal 9?

Many thanks.

Jordi

**Comment by greggmarshall** [comment]
There is a module called default_content that is often used for such without having to generate custom code.

 

Gregg Marshall, CPMR, CPSC

Speaker, Author, Consultant

 <http://www.vendor-tech.com/> Vendor-Tech, Inc.  

LinkedIn:   <http://www.linkedin.com/in/greggmarshall> http://www.linkedin.com/in/greggmarshall

 

From: Jordi ***@***.***> 
Sent: Saturday, September 24, 2022 11:54 AM
To: Labdoo/Labdoo-3.0 ***@***.***>
Cc: Gregg Marshall ***@***.***>; Mention ***@***.***>
Subject: [Labdoo/Labdoo-3.0] Creating nodes automatically at building time (Issue #24)

 

Hi @greggmarshall <https://github.com/greggmarshall>  ,

I would like to create a node automatically at building time. For instance, in Labdoo we have a hub called "Grassroots Hub" which is generic and should always exist. I would like this node (which is of content type "hub") to be created automatically when Labdoo 3.0 is being built and initialized. What is a good way to do this in Drupal 9?

Many thanks.

Jordi

**Comment by jrosgiralt** [comment]
Thanks. During installation of default_content I get this warning about a few packets being abandoned. Is this a concern?

````
gitpod /workspace/Labdoo-3.0 (main) $ ddev composer require drupal/default_content
Using version ^2.0@alpha for drupal/default_content
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update drupal/default_content
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking drupal/default_content (2.0.0-alpha2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading drupal/default_content (2.0.0-alpha2)
  - Installing drupal/default_content (2.0.0-alpha2): Extracting archive
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating autoload files
54 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
No security vulnerability advisories found
````

**Comment by greggmarshall** [comment]
Common for Drupal

 

Gregg Marshall, CPMR, CPSC

Speaker, Author, Consultant

 <http://www.vendor-tech.com/> Vendor-Tech, Inc.  

LinkedIn:   <http://www.linkedin.com/in/greggmarshall> http://www.linkedin.com/in/greggmarshall

**Comment by jrosgiralt** [comment]
Done. Se: https://github.com/Labdoo/Labdoo-3.0/blob/main/docs/labdoo-development-notes.md#exporting-default-content
