### ISSUE TITLE
Correct approach to safe PNG Files

### ISSUE THREAD

**Issue by jrosgiralt** [Labdoo/Labdoo-3.0#35]
Hi @greggmarshall,

In Drupal 7, i used to save the files in the folder “ /profiles/labdoo/files/pictures/“. For instance:

```/profiles/labdoo/files/pictures/photo-album-icon.png```

Example: https://github.com/Labdoo/Labdoo-2.0/blob/b64670d6aa44ced52286550903e1dc48d7b0fc13/modules/custom/labdoo_lib/labdoo_lib.module#L4831

What is the recommended way to store PNG files and similar (e.g., image files for icons, etc.) in Drupl 9? Thanks.

**Comment by greggmarshall** [comment]
I would put those files in the theme, in an images/ directory in the bootstrap_labdoo custom theme.

**Comment by jrosgiralt** [comment]
Thanks Gregg, I followed your advice.
